name: shadowlings
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    command:
      - npm
      - run
      - app:start
    working_dir: /src
    volumes:
      - ..:/src
    ports:
      - 3006:3006

  node:
    image: ghcr.io/paradigmxyz/foundry-alphanet:latest
    restart: always
    command:
      - --foundry-command
      - anvil
    ports:
      - 8545:8545

  bundler:
    build:
      context: .
      dockerfile: ./bundler/Dockerfile
    restart: always
    command:
      - --auto
      - --unsafe
      - --network=http://node:8545
      - --mnemonic=/data/mnemonic.txt
    environment:
      DEBUG: 'aa.exec,aa.exec.cron,aa.events,aa.mempool'
    ports:
      - 3000:3000
    volumes:
      - ./data/bundler:/data

  deploy:
    image: ghcr.io/paradigmxyz/foundry-alphanet:latest
    restart: on-failure:10
    command:
      - --foundry-command
      - 'forge script script/Deploy.s.sol:Deploy --rpc-url http://node:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast -vvv'
    working_dir: /src
    volumes:
      - ../contracts:/src
    depends_on:
      - node

  prefund:
    image: ghcr.io/paradigmxyz/foundry-alphanet:latest
    restart: on-failure:10
    command:
      - --foundry-command
      - 'forge script script/Prefunding.s.sol:Prefunding --rpc-url http://node:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast -vvv'
    working_dir: /src
    volumes:
      - ../contracts:/src
    depends_on:
      - node
      - bundler
