version: '3.8'

services:
  node:
    image: ghcr.io/paradigmxyz/foundry-alphanet:latest
    restart: always
    command:
      - --foundry-command
      - anvil
    ports:
      - 8545:8545

  bundler:
    build:
      context: .
      dockerfile: bundler/Dockerfile
    restart: always
    command:
      - --auto
      - --unsafe
      - --network=http://node:8545
      - --mnemonic=/data/mnemonic.txt
    environment:
      DEBUG: 'aa.exec,aa.exec.cron,aa.events,aa.mempool'
    ports:
      - 3000:3000
    volumes:
      - ./data/bundler:/data
