[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
remappings = [
    "account-abstraction/=lib/account-abstraction/contracts/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
  otim = "http://devnet.otim.xyz"
